#!/usr/bin/env python3
"""ENEX → markdown converter, stdlib only. One .enex file = one exported Evernote
notebook (the Principal exports: Evernote → notebook → Export → .enex).

Layout (see .gitignore — CONTENT never enters git, only the index):
  evernote/raw/   the .enex files            (gitignored)
  evernote/md/    one .md per note           (gitignored)
  evernote/INDEX.md  regenerated inventory   (COMMITTED)

Each note becomes markdown with a header block: title, notebook, created, updated,
tags, source-url, attachment count (binaries are NOT extracted — the count is the
signal to open Evernote for the original). Content is a plain-text rendering of the
en-note XHTML: headings/paragraphs/line breaks/list items become lines, tables become
pipe-rows, everything else is stripped.

Usage:
  python3 scripts/enex_to_md.py evernote/raw/*.enex     # convert + rebuild INDEX.md
  python3 scripts/enex_to_md.py --index-only            # rebuild INDEX.md only
"""
import os, re, sys, glob, html, datetime
import xml.etree.ElementTree as ET
from html.parser import HTMLParser

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD_DIR = os.path.join(ROOT, 'evernote', 'md')
INDEX = os.path.join(ROOT, 'evernote', 'INDEX.md')

BLOCK_TAGS = {'div', 'p', 'br', 'li', 'tr', 'h1', 'h2', 'h3', 'h4', 'blockquote',
              'en-note'}

class _Text(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts, self.in_td = [], False
    def handle_starttag(self, tag, attrs):
        if tag in BLOCK_TAGS: self.parts.append('\n')
        if tag == 'li': self.parts.append('- ')
        if tag == 'td': self.in_td = True; self.parts.append(' | ')
        if tag == 'en-media': self.parts.append('[attachment]')
        if tag == 'en-todo':
            done = dict(attrs).get('checked') == 'true'
            self.parts.append('[x] ' if done else '[ ] ')
    def handle_endtag(self, tag):
        if tag == 'td': self.in_td = False
        if tag in BLOCK_TAGS: self.parts.append('\n')
    def handle_data(self, data):
        self.parts.append(data)

def note_text(content_xml):
    p = _Text()
    try: p.feed(content_xml)
    except Exception: return re.sub(r'<[^>]+>', ' ', content_xml)
    txt = ''.join(p.parts)
    txt = re.sub(r'[ \t]+', ' ', txt)
    return re.sub(r'\n{3,}', '\n\n', txt).strip()

def _dt(s):
    if not s: return ''
    try:
        return datetime.datetime.strptime(s, '%Y%m%dT%H%M%SZ').date().isoformat()
    except ValueError:
        return s

def slug(s, n=60):
    s = re.sub(r'[^A-Za-z0-9]+', '-', (s or 'untitled')).strip('-').lower()
    return s[:n] or 'untitled'

def convert(enex_path):
    notebook = slug(os.path.splitext(os.path.basename(enex_path))[0])
    outdir = os.path.join(MD_DIR, notebook)
    os.makedirs(outdir, exist_ok=True)
    written = 0
    # iterparse: 6,000 notes must not need the whole file in memory
    for _, el in ET.iterparse(enex_path):
        if el.tag != 'note': continue
        title = (el.findtext('title') or 'untitled').strip()
        created, updated = _dt(el.findtext('created')), _dt(el.findtext('updated'))
        tags = [t.text for t in el.findall('tag') if t.text]
        src = el.findtext('note-attributes/source-url') or ''
        n_res = len(el.findall('resource'))
        body = note_text(el.findtext('content') or '')
        written += 1
        head = [f'# {title}', '',
                f'- notebook: {notebook}',
                f'- created: {created} · updated: {updated}',
                f'- tags: {", ".join(tags) if tags else "—"}',
                f'- attachments: {n_res} (not extracted — open Evernote for originals)']
        if src: head.append(f'- source-url: {src}')
        path = os.path.join(outdir, f'{written:04d}-{slug(title)}.md')
        with open(path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(head) + '\n\n' + body + '\n')
        el.clear()
    return notebook, written

def rebuild_index():
    lines = ['<!-- GENERATED by scripts/enex_to_md.py — never hand-edit -->',
             f'# Evernote import inventory — regenerated {datetime.date.today().isoformat()}',
             '',
             'Content lives OUTSIDE git (evernote/md/, gitignored); this index is the',
             'committed record of what exists. Triage state lives in the triage log,',
             'not here (see /evernote-triage).', '']
    total = 0
    for nb in sorted(os.listdir(MD_DIR)) if os.path.isdir(MD_DIR) else []:
        files = sorted(glob.glob(os.path.join(MD_DIR, nb, '*.md')))
        if not files: continue
        total += len(files)
        lines.append(f'## {nb} — {len(files)} notes')
        for fp in files:
            first = open(fp, encoding='utf-8').readline().lstrip('# ').strip()
            rel = os.path.relpath(fp, ROOT)
            lines.append(f'- `{rel}` — {html.escape(first)}')
        lines.append('')
    lines.insert(3, f'**{total} notes converted.**')
    os.makedirs(os.path.dirname(INDEX), exist_ok=True)
    open(INDEX, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
    return total

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if '--index-only' not in sys.argv:
        if not args:
            raise SystemExit('usage: enex_to_md.py <file.enex ...> | --index-only')
        for p in args:
            nb, n = convert(p)
            print(f'{nb}: {n} notes -> evernote/md/{nb}/')
    total = rebuild_index()
    print(f'INDEX.md rebuilt: {total} notes total')
